{ stateVersion, ... }: {
  home.stateVersion = stateVersion;
  programs.home-manager.enable = true;

  programs.zsh = {
    enable = true;
    initExtraFirst = ''
      # @generated by Home Manager
    '';
  };

  programs.vscode = {
    enable = true;
    userSettings = builtins.fromJSON (builtins.readFile ../cfg/vscode.json);
  };
}
