{
  stateVersion,
  pkgs,
  ...
}: let
  genMsg = "# @generated by Home Manager";

  utils = import ../utils.nix;
  sharedResources = utils.sharedResources pkgs;
in {
  home.stateVersion = stateVersion;
  programs.home-manager.enable = true;

  xdg.configFile."starship.toml".source = ../gen/starship.toml;
  home.file.".face".source = "${sharedResources}/face.jpg";

  programs.zsh = {
    enable = true;
    initExtraFirst = ''
      ${genMsg}
    '';
  };

  programs.bash = {
    enable = true;
    initExtra = ''
      ${genMsg}
    '';
  };

  programs.vscode = {
    enable = true;
    userSettings = builtins.fromJSON (builtins.readFile ../cfg/vsc.jsonc);
  };

  programs.kitty = {
    enable = true;
    settings = {shell = "zsh";};
  };
}
