{stateVersion, ...}: let
  genMsg = "# @generated by Home Manager";
in {
  home.stateVersion = stateVersion;
  programs.home-manager.enable = true;

  xdg.configFile."background-image.jpg".source = ../cfg/bgi.jpg;
  xdg.configFile."starship.toml".source = ../gen/starship.toml;

  programs.zsh = {
    enable = true;
    initExtraFirst = ''
      ${genMsg}
    '';
  };

  programs.bash = {
    enable = true;
    initExtra = ''
      ${genMsg}
    '';
  };

  programs.vscode = {
    enable = true;
    userSettings = builtins.fromJSON (builtins.readFile ../cfg/vsc.jsonc);
  };

  programs.kitty = {
    enable = true;
    settings = {shell = "zsh";};
  };
}
